# Site settings
title: BlipKit Soundchip Library
short_title: BlipKit Library
email: simon@monoxid.net
description: "BlipKit is a C library for creating the beautiful sound of old soundchips. It generates various waveforms, supports effects and instruments can be used to create envelopes."
baseurl: "/BlipKit"
url: "http://detomon.github.io"
github_username: detomon

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: css

navigation:
 - title: Manual
   url: /manual/
 - title: Examples
   url: /examples/
 - title: Download
   url: /download/
