# Site settings
title: BlipKit Soundchip Library
short_title: BlipKit
email: simon@monoxid.net
description: "BlipKit is a C library for creating the beautiful sound of old soundchips. It generates various waveforms and supports effects. Instruments can be used to create envelopes. Samples can be loaded and played in different pitches."
baseurl: "/BlipKit"
url: "http://detomon.github.io"
github_username:  detomon

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: css
